-- Flyway migration V3: таблица пользователей для аутентификации
-- Роли: ADMIN, USER (H2 и PostgreSQL)

CREATE TABLE IF NOT EXISTS app_users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    CONSTRAINT check_role CHECK (role IN ('ADMIN', 'USER'))
);

CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);
